### ISSUE TITLE
【求助帖】又忘记了网页中的框用css怎么写!

### ISSUE THREAD

**Issue by blacklike** [zptcsoft/zptcsoft.github.io#159]
又忘记了网页中的框用css怎么写!

**Comment by zptcsoft** [comment]
```css
div{
    border:1px solid #000;
}
````
使用css的边框属性，可以参考[手册](//zptcsoft.github.io/css3/)。
